development: &default
  adapter: postgresql
  database: THUDHack_development
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000
  username: postgres
  password: <%= ENV['THUDHACK_DATABASE_PASSWORD'] %>

test: &test
  <<: *default
  database: THUDHack_test

production:
  <<: *default
  database: THUDHack_production
  username: THUDHack
  password: <%= ENV['THUDHACK_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
